# Configuración de la fecha de reporte COVID
covid.report.date=2022-04-16
# País ejemplo para mostrar datos agrupados
covid.example.country=CHN
# Tiempo de espera para iniciar el procesamiento (segundos)
covid.processing.delay=15